### use balance 1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000003",
  "amount": 100
}

### use balance 2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000003",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "5a55c3f141fe40f6bc646fb0199dc621",
  "accountNumber": "1000000003",
  "amount": 12345
}

### query transaction
GET http://localhost:8080/transaction/c0c0d133ae9040a7b13afc2f9516dc12